"""Fictional, deterministic seed data for the local meeting-ready demo."""

from __future__ import annotations

SEED_TIMESTAMP = "2026-08-30T14:00:00Z"

POLICIES = [
    {
        "id": "pol-commerce-balanced-v3",
        "name": "Mercury Market balanced value",
        "domain": "commerce",
        "purpose": "help people find useful products they are likely to value",
        "status": "active",
        "objective_weights": {
            "relevance": 0.34,
            "quality": 0.22,
            "user_value": 0.17,
            "diversity": 0.12,
            "freshness": 0.08,
            "satisfaction": 0.04,
            "safety": 0.03,
        },
        "exploration_rate": 0.015,
        "allowed_candidate_features": [
            "relevance",
            "quality",
            "user_value",
            "diversity",
            "freshness",
            "satisfaction",
            "safety",
        ],
        "constraints": {"candidate_safety_floor": 0.70},
        "version": 3,
    },
    {
        "id": "pol-commerce-value-v4",
        "name": "Mercury Market durable value",
        "domain": "commerce",
        "purpose": "help people find useful products they are likely to value",
        "status": "active",
        "objective_weights": {
            "relevance": 0.30,
            "quality": 0.24,
            "user_value": 0.22,
            "diversity": 0.10,
            "freshness": 0.06,
            "satisfaction": 0.05,
            "safety": 0.03,
        },
        "exploration_rate": 0.02,
        "allowed_candidate_features": [
            "relevance",
            "quality",
            "user_value",
            "diversity",
            "freshness",
            "satisfaction",
            "safety",
        ],
        "constraints": {"candidate_safety_floor": 0.72},
        "version": 4,
    },
    {
        "id": "pol-media-depth-v2",
        "name": "Northstar Media trusted discovery",
        "domain": "media",
        "purpose": "surface relevant and trustworthy stories without maximizing compulsion",
        "status": "active",
        "objective_weights": {
            "relevance": 0.30,
            "quality": 0.24,
            "diversity": 0.17,
            "freshness": 0.12,
            "trust": 0.10,
            "satisfaction": 0.04,
            "safety": 0.03,
        },
        "exploration_rate": 0.02,
        "allowed_candidate_features": [
            "relevance",
            "quality",
            "diversity",
            "freshness",
            "trust",
            "satisfaction",
            "safety",
        ],
        "constraints": {"candidate_safety_floor": 0.78},
        "version": 2,
    },
    {
        "id": "pol-media-breadth-v3",
        "name": "Northstar Media broader discovery",
        "domain": "media",
        "purpose": "surface relevant and trustworthy stories without maximizing compulsion",
        "status": "active",
        "objective_weights": {
            "relevance": 0.24,
            "quality": 0.23,
            "diversity": 0.23,
            "freshness": 0.12,
            "trust": 0.10,
            "satisfaction": 0.05,
            "safety": 0.03,
        },
        "exploration_rate": 0.055,
        "allowed_candidate_features": [
            "relevance",
            "quality",
            "diversity",
            "freshness",
            "trust",
            "satisfaction",
            "safety",
        ],
        "constraints": {"candidate_safety_floor": 0.78},
        "version": 3,
    },
    {
        "id": "pol-community-helpful-v1",
        "name": "CommonGround helpful participation",
        "domain": "community",
        "purpose": "connect members with constructive and relevant community contributions",
        "status": "active",
        "objective_weights": {
            "relevance": 0.28,
            "quality": 0.24,
            "trust": 0.18,
            "diversity": 0.13,
            "freshness": 0.08,
            "satisfaction": 0.05,
            "safety": 0.04,
        },
        "exploration_rate": 0.01,
        "allowed_candidate_features": [
            "relevance",
            "quality",
            "trust",
            "diversity",
            "freshness",
            "satisfaction",
            "safety",
        ],
        "constraints": {"candidate_safety_floor": 0.82},
        "version": 1,
    },
    {
        "id": "pol-community-trust-v2",
        "name": "CommonGround trust-forward",
        "domain": "community",
        "purpose": "connect members with constructive and relevant community contributions",
        "status": "active",
        "objective_weights": {
            "relevance": 0.24,
            "quality": 0.25,
            "trust": 0.23,
            "diversity": 0.11,
            "freshness": 0.07,
            "satisfaction": 0.05,
            "safety": 0.05,
        },
        "exploration_rate": 0.02,
        "allowed_candidate_features": [
            "relevance",
            "quality",
            "trust",
            "diversity",
            "freshness",
            "satisfaction",
            "safety",
        ],
        "constraints": {"candidate_safety_floor": 0.84},
        "version": 2,
    },
]

COHORTS = [
    {
        "id": "cohort-commerce-returning",
        "name": "Returning storefront visitors",
        "domain": "commerce",
        "purpose": "help people find useful products they are likely to value",
        "description": "People returning to a fictional general-goods storefront.",
        "estimated_size": 18_420,
        "status": "eligible",
    },
    {
        "id": "cohort-media-weekend",
        "name": "Weekend topic explorers",
        "domain": "media",
        "purpose": "surface relevant and trustworthy stories without maximizing compulsion",
        "description": "Readers intentionally browsing outside their usual topics.",
        "estimated_size": 12_860,
        "status": "eligible",
    },
    {
        "id": "cohort-community-contributors",
        "name": "New community contributors",
        "domain": "community",
        "purpose": "connect members with constructive and relevant community contributions",
        "description": "Pseudonymous members in their first month of participation.",
        "estimated_size": 3_940,
        "status": "eligible",
    },
    {
        "id": "cohort-commerce-small-pilot",
        "name": "Small specialty pilot",
        "domain": "commerce",
        "purpose": "help people find useful products they are likely to value",
        "description": "Intentionally undersized demo cohort used to prove privacy suppression.",
        "estimated_size": 34,
        "status": "privacy_blocked",
    },
]

EXPERIMENTS = [
    {
        "id": "exp-commerce-durable-value",
        "name": "Durable value over short-term conversion",
        "domain": "commerce",
        "purpose": "help people find useful products they are likely to value",
        "hypothesis": (
            "Increasing quality and durable value weight will improve satisfaction "
            "without increasing reports."
        ),
        "status": "running",
        "control_policy_id": "pol-commerce-balanced-v3",
        "treatment_policy_id": "pol-commerce-value-v4",
        "cohort_id": "cohort-commerce-returning",
        "traffic_percent": 4.0,
        "treatment_share": 0.5,
        "risk_level": "low",
        "risk_reasons": [],
        "guardrails": {
            "min_quality_score": 0.72,
            "max_harm_rate": 0.02,
            "max_complaint_rate": 0.03,
            "min_fairness_ratio": 0.82,
        },
        "started_at": "2026-08-28T16:00:00Z",
    },
    {
        "id": "exp-media-broader-discovery",
        "name": "Broader trustworthy discovery",
        "domain": "media",
        "purpose": "surface relevant and trustworthy stories without maximizing compulsion",
        "hypothesis": (
            "A bounded increase in diversity can improve discovery satisfaction "
            "while preserving trust and quality."
        ),
        "status": "pending_approval",
        "control_policy_id": "pol-media-depth-v2",
        "treatment_policy_id": "pol-media-breadth-v3",
        "cohort_id": "cohort-media-weekend",
        "traffic_percent": 12.0,
        "treatment_share": 0.5,
        "risk_level": "high",
        "risk_reasons": [
            "traffic 12.0% exceeds the 5.0% autonomous launch cap",
            "exploration 5.5% exceeds the 3.0% low-risk threshold",
        ],
        "guardrails": {
            "min_quality_score": 0.75,
            "max_harm_rate": 0.015,
            "max_complaint_rate": 0.025,
            "min_fairness_ratio": 0.82,
        },
        "started_at": None,
    },
    {
        "id": "exp-community-trust",
        "name": "Trust-forward contribution ranking",
        "domain": "community",
        "purpose": "connect members with constructive and relevant community contributions",
        "hypothesis": (
            "A trust-forward ranking will improve constructive participation "
            "without narrowing contribution diversity."
        ),
        "status": "running",
        "control_policy_id": "pol-community-helpful-v1",
        "treatment_policy_id": "pol-community-trust-v2",
        "cohort_id": "cohort-community-contributors",
        "traffic_percent": 3.0,
        "treatment_share": 0.5,
        "risk_level": "low",
        "risk_reasons": [],
        "guardrails": {
            "min_quality_score": 0.74,
            "max_harm_rate": 0.012,
            "max_complaint_rate": 0.02,
            "min_fairness_ratio": 0.84,
        },
        "started_at": "2026-08-29T14:30:00Z",
    },
    {
        "id": "exp-commerce-small-pilot",
        "name": "Small cohort privacy-floor proof",
        "domain": "commerce",
        "purpose": "help people find useful products they are likely to value",
        "hypothesis": (
            "This intentionally undersized experiment must be prevented from launching."
        ),
        "status": "draft",
        "control_policy_id": "pol-commerce-balanced-v3",
        "treatment_policy_id": "pol-commerce-value-v4",
        "cohort_id": "cohort-commerce-small-pilot",
        "traffic_percent": 2.0,
        "treatment_share": 0.5,
        "risk_level": "low",
        "risk_reasons": ["cohort is below the minimum privacy floor"],
        "guardrails": {
            "min_quality_score": 0.72,
            "max_harm_rate": 0.02,
            "max_complaint_rate": 0.03,
            "min_fairness_ratio": 0.82,
        },
        "started_at": None,
    },
]

APPROVALS = [
    {
        "id": "apr-media-broader-discovery",
        "resource_type": "experiment",
        "resource_id": "exp-media-broader-discovery",
        "action": "launch",
        "status": "pending",
        "risk_level": "high",
        "reasons": [
            "traffic 12.0% exceeds the 5.0% autonomous launch cap",
            "exploration 5.5% exceeds the 3.0% low-risk threshold",
        ],
        "requested_by": "maya-chen",
        "requested_at": "2026-08-30T13:20:00Z",
    },
    {
        "id": "apr-commerce-durable-value",
        "resource_type": "experiment",
        "resource_id": "exp-commerce-durable-value",
        "action": "launch",
        "status": "approved",
        "risk_level": "low",
        "reasons": ["operator review recorded for the demo portfolio"],
        "requested_by": "sam-rivera",
        "requested_at": "2026-08-28T15:35:00Z",
        "decided_by": "lee-okafor",
        "decided_at": "2026-08-28T15:48:00Z",
        "decision_reason": "Cohort, purpose, and guardrails verified.",
    },
]

METRICS = [
    {
        "experiment_id": "exp-commerce-durable-value",
        "cohort_id": "cohort-commerce-returning",
        "metric_name": "quality_score",
        "variant": "control",
        "sample_size": 642,
        "value": 0.781,
    },
    {
        "experiment_id": "exp-commerce-durable-value",
        "cohort_id": "cohort-commerce-returning",
        "metric_name": "quality_score",
        "variant": "treatment",
        "sample_size": 631,
        "value": 0.806,
    },
    {
        "experiment_id": "exp-commerce-durable-value",
        "cohort_id": "cohort-commerce-returning",
        "metric_name": "satisfaction",
        "variant": "treatment",
        "sample_size": 588,
        "value": 0.744,
    },
    {
        "experiment_id": "exp-commerce-durable-value",
        "cohort_id": "cohort-commerce-returning",
        "metric_name": "fairness_ratio",
        "variant": "aggregate",
        "sample_size": 1_273,
        "value": 0.91,
    },
    {
        "experiment_id": "exp-community-trust",
        "cohort_id": "cohort-community-contributors",
        "metric_name": "quality_score",
        "variant": "treatment",
        "sample_size": 214,
        "value": 0.769,
    },
    {
        "experiment_id": "exp-community-trust",
        "cohort_id": "cohort-community-contributors",
        "metric_name": "fairness_ratio",
        "variant": "aggregate",
        "sample_size": 418,
        "value": 0.86,
    },
    {
        "experiment_id": "exp-commerce-small-pilot",
        "cohort_id": "cohort-commerce-small-pilot",
        "metric_name": "quality_score",
        "variant": "treatment",
        "sample_size": 21,
        "value": 0.91,
    },
]

DEMO_CANDIDATES = {
    "commerce": [
        {
            "id": "item-aurora-kettle",
            "features": {
                "relevance": 0.92,
                "quality": 0.88,
                "user_value": 0.81,
                "diversity": 0.54,
                "freshness": 0.61,
                "satisfaction": 0.85,
                "safety": 0.98,
            },
            "metadata": {"label": "Aurora temperature-control kettle", "source": "home"},
        },
        {
            "id": "item-moss-repair-kit",
            "features": {
                "relevance": 0.76,
                "quality": 0.93,
                "user_value": 0.95,
                "diversity": 0.82,
                "freshness": 0.48,
                "satisfaction": 0.88,
                "safety": 0.99,
            },
            "metadata": {"label": "Moss household repair kit", "source": "utility"},
        },
        {
            "id": "item-cinder-speaker",
            "features": {
                "relevance": 0.88,
                "quality": 0.72,
                "user_value": 0.58,
                "diversity": 0.43,
                "freshness": 0.91,
                "satisfaction": 0.69,
                "safety": 0.96,
            },
            "metadata": {"label": "Cinder pocket speaker", "source": "audio"},
        },
        {
            "id": "item-nova-supplement",
            "features": {
                "relevance": 0.96,
                "quality": 0.67,
                "user_value": 0.71,
                "diversity": 0.52,
                "freshness": 0.96,
                "satisfaction": 0.64,
                "safety": 0.41,
            },
            "metadata": {"label": "Nova unverified supplement", "source": "wellness"},
        },
    ],
    "media": [
        {
            "id": "story-civic-gardens",
            "features": {
                "relevance": 0.84,
                "quality": 0.91,
                "diversity": 0.78,
                "freshness": 0.66,
                "trust": 0.95,
                "satisfaction": 0.82,
                "safety": 0.99,
            },
            "metadata": {"label": "How civic gardens changed three neighborhoods"},
        },
        {
            "id": "story-ocean-mapping",
            "features": {
                "relevance": 0.73,
                "quality": 0.94,
                "diversity": 0.93,
                "freshness": 0.78,
                "trust": 0.96,
                "satisfaction": 0.86,
                "safety": 0.99,
            },
            "metadata": {"label": "The quiet revolution in ocean mapping"},
        },
        {
            "id": "story-studio-profile",
            "features": {
                "relevance": 0.90,
                "quality": 0.76,
                "diversity": 0.51,
                "freshness": 0.89,
                "trust": 0.79,
                "satisfaction": 0.80,
                "safety": 0.97,
            },
            "metadata": {"label": "Inside an independent animation studio"},
        },
    ],
    "community": [
        {
            "id": "post-library-tool-share",
            "features": {
                "relevance": 0.88,
                "quality": 0.92,
                "trust": 0.95,
                "diversity": 0.68,
                "freshness": 0.72,
                "satisfaction": 0.84,
                "safety": 0.99,
            },
            "metadata": {"label": "Neighborhood library tool-share guide"},
        },
        {
            "id": "post-transit-feedback",
            "features": {
                "relevance": 0.79,
                "quality": 0.87,
                "trust": 0.91,
                "diversity": 0.85,
                "freshness": 0.91,
                "satisfaction": 0.79,
                "safety": 0.98,
            },
            "metadata": {"label": "Constructive transit feedback template"},
        },
        {
            "id": "post-viral-rumor",
            "features": {
                "relevance": 0.97,
                "quality": 0.31,
                "trust": 0.20,
                "diversity": 0.40,
                "freshness": 0.99,
                "satisfaction": 0.52,
                "safety": 0.34,
            },
            "metadata": {"label": "Unverified viral rumor"},
        },
    ],
}
